# -*- mode:ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :staging do |staging|
    staging.vm.box = "centos64"
    staging.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"
    staging.vm.network :private_network, ip: "192.168.50.10"
    staging.vm.provision :puppet do |puppet|
      puppet.module_path = "."
      puppet.manifests_path = "."
      puppet.manifest_file = "staging.pp"
      puppet.facter = {
        "production" => "192.168.50.11",
        "development" => "192.168.50.12",
        "hostname" => "staging",
        "is_master" => true,
        "master_private_key" => "-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEA2Iu8HwvXTSmlCzo5o8yBVk4Lgvq/6CesatTySO06hKOoWmtz
ib2YsYl3dusmyYQegGMqYFcY8BOk9dav/eepi0togvXm/x66RngYrAsJQS4zbrSt
bJKTwP07IaA9W7PazCWC3HjLghiK83zHdd9arnaMYn8tHwqAeY6H6NvwnXtu0aJ8
PyACdTIbUIZUWZLhP52xmBd+hxIPOYOSvFJSLP8ZZLjsvMwPYTkQyslnLqqFyjul
nrwgBUApCRpwXLQ/ToZ/mLI2s+siuEwdj8WuEen33s6SYgJv5s4WRf5635YkNsZp
WrLMv9bLK07d+cvi0AwKJoGcnOtC6uMxEjsu0QIBIwKCAQBKPomkPpL14mR44MNO
Gjr5BNC/MWZeOXzxbZTlza2p0bYQX1rQI79S0AuzvlZw+hkWE178daImbSKdbi22
I4qWKHuanXPFLxtLXGA6/Hgzms/OL1FnDa8AVtJx7cvk7TUSywhLlyEz6yhTez0S
eHbcuu5Np/I2h0H9yne9jTyNw0oHkmI53p24NcHeB96Svmkma4FU657zRWsmRUKA
dM4w+FhzTSvspcxnerYILaPRuJKjoGX919WByX9+pk4DabNehIneggzzn4MG1Je+
zdTnkYn2Yg7F9FSFhfvixvfFrO1GPKGA9MYFer9LHmL8Y2AnltLv/X8+ByflmFCd
uO8bAoGBAOxX+kyMa9uMiLDF7YbnQ/5KrfEeVGzm9NkZYghUCpxCzwYOmFpcZQr1
XHGT6rivG6VdKMKmexNrvYzU3McbPeatlw5ubpNs1ieF697uy4GnwE3jn8yw0qRF
Zj+AUpWuDXYjJ/AytM6u0VZh5aAJiCoPlrjmk6iOJC71+dnWAZk3AoGBAOqOPTvf
QDA6DJ/DAdmbo4WaNjHsvoIFPWhF14hxnbHbW7wF1NJDg3A+DAxJruYGid9lKbl+
i4iJoZMC2JsM12LNQjRhSFLV2RJedC60dyocFoJB5hqafH/GoQ1wPOfbpaSxbaIa
iWcrtMbY+0fldzWiUr9ZSpZEh4pB7RbFiNw3AoGAUQg4j0YWWecKSzyL870BXoAB
H3gc8iNMojSWo8UK878iaHoIWX7DjrqGGE/4tFlLTqOY8ke1Kzrh5yRo887TZQhR
DEMemPIdieTF5gi6zV4WDBOHPt2KDG+QxVCRV+PnW7RINRizBQi8zSjhA6t/JF0d
u7zE6VVOO/yQLW3x62MCgYEA49qh4mPX9FWl3QaUFTgbMVP6Id6qb61RmH5cWKji
VQD6Bxubim14Xmgo9f5vYxxLa0xUaw03FuwZTPtzVMqlWKojDk/f23Cm++a6AXwb
/QVXsbxb31Q+bX8gG67cFG74rp269T5Zl2xJNjHeKJXEQrrxTCravdwr5WSdLBBZ
EG8CgYEAyh10O99ph3eqeBlwFL0NM433vAVsT0iHU85jhwO4aajAhRo/nn7d2TQD
erYer12Rdh+2/lgan38xbwzwOXDPi3Z2GvAJchrMiJtTu4EzUaQRU0ff3ymCwsW4
orqC776CwSyKBpobOubuQq3RHa5gmpwKXbFPArrtbrsF0eBlYmA=
-----END RSA PRIVATE KEY-----",
        "master_public_key" => "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA2Iu8HwvXTSmlCzo5o8yBVk4Lgvq/6CesatTySO06hKOoWmtzib2YsYl3dusmyYQegGMqYFcY8BOk9dav/eepi0togvXm/x66RngYrAsJQS4zbrStbJKTwP07IaA9W7PazCWC3HjLghiK83zHdd9arnaMYn8tHwqAeY6H6NvwnXtu0aJ8PyACdTIbUIZUWZLhP52xmBd+hxIPOYOSvFJSLP8ZZLjsvMwPYTkQyslnLqqFyjulnrwgBUApCRpwXLQ/ToZ/mLI2s+siuEwdj8WuEen33s6SYgJv5s4WRf5635YkNsZpWrLMv9bLK07d+cvi0AwKJoGcnOtC6uMxEjsu0Q== vagrant@localhost.localdomain",
      }
    end
  end
  config.vm.define :production do |production|
    production.vm.box = "centos64"
    production.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"
    production.vm.network :private_network, ip: "192.168.50.11"
    production.vm.provision :puppet do |puppet|
      puppet.module_path = "."
      puppet.manifests_path = "."
      puppet.manifest_file = "production.pp"
      puppet.facter = {
        "master_public_key" => "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA2Iu8HwvXTSmlCzo5o8yBVk4Lgvq/6CesatTySO06hKOoWmtzib2YsYl3dusmyYQegGMqYFcY8BOk9dav/eepi0togvXm/x66RngYrAsJQS4zbrStbJKTwP07IaA9W7PazCWC3HjLghiK83zHdd9arnaMYn8tHwqAeY6H6NvwnXtu0aJ8PyACdTIbUIZUWZLhP52xmBd+hxIPOYOSvFJSLP8ZZLjsvMwPYTkQyslnLqqFyjulnrwgBUApCRpwXLQ/ToZ/mLI2s+siuEwdj8WuEen33s6SYgJv5s4WRf5635YkNsZpWrLMv9bLK07d+cvi0AwKJoGcnOtC6uMxEjsu0Q== vagrant@localhost.localdomain",
        "hostname" => "production",
      }
    end
  end
  config.vm.define :development do |development|
    development.vm.box = "centos64"
    development.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"
    development.vm.network :private_network, ip: "192.168.50.12"
    development.vm.provision :puppet do |puppet|
      puppet.module_path = "."
      puppet.manifests_path = "."
      puppet.manifest_file = "production.pp"
      puppet.facter = {
        "master_public_key" => "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA2Iu8HwvXTSmlCzo5o8yBVk4Lgvq/6CesatTySO06hKOoWmtzib2YsYl3dusmyYQegGMqYFcY8BOk9dav/eepi0togvXm/x66RngYrAsJQS4zbrStbJKTwP07IaA9W7PazCWC3HjLghiK83zHdd9arnaMYn8tHwqAeY6H6NvwnXtu0aJ8PyACdTIbUIZUWZLhP52xmBd+hxIPOYOSvFJSLP8ZZLjsvMwPYTkQyslnLqqFyjulnrwgBUApCRpwXLQ/ToZ/mLI2s+siuEwdj8WuEen33s6SYgJv5s4WRf5635YkNsZpWrLMv9bLK07d+cvi0AwKJoGcnOtC6uMxEjsu0Q== vagrant@localhost.localdomain",
        "hostname" => "development",
      }
    end
  end
end

